REVOKE ALL ON FUNCTION public.current_user_role() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_admin_or_coordinator(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_class_teacher_of(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_own_student(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_parent_of_student(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.my_children_ids(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.parent_child_class_id(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.parent_of_class(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.student_class_id(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.teacher_profile_id(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.teacher_teaches_class(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.teacher_teaches_subject(uuid, uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.user_in_class(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.user_in_exam(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.user_sees_teacher(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.touch_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.validate_exam_paper_date() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_role() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin_or_coordinator(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_class_teacher_of(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_own_student(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_parent_of_student(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.my_children_ids(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.parent_child_class_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.parent_of_class(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.student_class_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.teacher_profile_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.teacher_teaches_class(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.teacher_teaches_subject(uuid, uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_in_class(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_in_exam(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_sees_teacher(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.touch_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_exam_paper_date() TO service_role;